### ISSUE TITLE
checklist for Express apps on Azure

### ISSUE THREAD

**Issue by dwhieb** [dwhieb/utilities#13]
# Checklist Items for Express Apps on Azure

## package.json

- [ ] The `"main"` field should point to the entry point for the app (usually `app.js`)

- [ ] Node engines should be specified in the `"engines"` field

## app.js settings

- [ ] do init and config in separate files, e.g.:
  - authenticate.js
  - config.js
  - errors.js
  - handlebars.js
  - limiter.js
  - logger.js
  - mendeley.js
  - passport.js
  - router.js
  - server.js
  - socket.js

- [ ] trust proxy

  ```js
  app.enable(`trust proxy`);
  ```

- [ ] declare Handlebars engine and file extension

  ```js
  app.engine(extname, handlebars.engine);
  ```

- [ ] log server information when app starts
  - [ ] `Server started. Press Ctrl+C to terminate.`
  - [ ] Project
  - [ ] Port
  - [ ] Time
  - [ ] Node Version
  - [ ] Env

## Middleware

- [ ] authentication (if needed)

- [ ] helmet - security

- [ ] rate limiting (e.g. with [express-rate-limit][2])

- [ ] routing for static files

  ```js
  express.static(path.join(__dirname, `/public`));
  ```

## Logging & Error Handling

- [ ] 404 and 500 handlers (should come last in the waterfall)

  ```js
  // 404 handler
  const error404 = (req, res, next) => {
    // render error page with 404 status
  };

  // 500 handler
  const error500 = (err, req, res, next) => {
    // render error page with 500 status and error ID
    // log and report errors
  };
  ```

- [ ] generic error handler for server

  ```js
  server.on(`error`, err => {
    // log and report error
  });
  ```

- [ ] standardized error handling
  - [ ] standardized messages (e.g. with [Boom][1])
  - [ ] `res.error` middleware
  - [ ] convert errors from third-party services (be thorough)

- [ ] provide an option to log requested URL with an environment variable
  - The log should happen after static files are sent

- [ ] provide an option to log server errors with an environment variable

[1]: https://www.npmjs.com/package/boom
[2]: https://www.npmjs.com/package/express-rate-limit
